spring.application.name=APIBiblioteca
debug=false
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# 1. Credenciales de la Base de Datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' lee tus clases Java y crea o modifica las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
# Esto imprimirá en la consola el código SQL puro que Hibernate genera por ti
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# agrupar los INSERTS en bloques
spring.jpa.properties.hibernate.jdbc.batch_size=100
# también los UPDATES
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

logging.level.org.hibernate.orm.jdbc.batch=trace
logging.level.org.hibernate.engine.jdbc.batch.internal.BatchingBatch=debug

google.books.api.key=${GOOGLE_BOOKS_API_KEY}